name: super_value_notifier
description: "A Super Value Notifier for Flutter"
version: 0.0.3
homepage: "https://github.com/Eronildo/super_value_notifier"

environment:
  sdk: ^3.5.4
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  collection: ^1.18.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
